/**
 * Comprehensive Services & Solutions Data for Working Dots
 */

export const SERVICES_DATA = [
  {
    id: 'web',
    slug: 'website-development',
    category: 'Web Platforms',
    tag: 'Web & Platforms',
    title: 'Website & Full-Stack Web Development',
    shortDesc: 'We engineer high-performance, conversion-focused websites and scalable web applications designed around your business goals.',
    fullDesc: 'From high-converting brand flagships to complex enterprise SaaS dashboards, our engineering team crafts web platforms with modern React, Next.js, and edge-native architectures. We optimize every millisecond of page load time, implement airtight security, and design fluid responsive experiences across all viewports.',
    sla: '7–14 Days Typical Sprint',
    deliverables: [
      'React 19 & Next.js 15 High-Speed Web Applications',
      'Custom Headless CMS & Enterprise Admin Dashboards',
      'Lightning Fast 99+ Google Lighthouse Page Load Scores',
      'SEO & Conversion Rate Optimization (CRO) Architecture',
      'High-Concurrency RESTful & GraphQL API Integrations',
      'Stripe & Razorpay Multi-Currency Payment Gateways',
      'Multi-Tier Role-Based Access Control (RBAC)',
    ],
    techStack: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Supabase', 'Tailwind/CSS', 'Vercel Edge'],
    features: [
      { title: 'Sub-Second Speeds', desc: 'Edge-rendered micro-frontend architecture ensuring instant global access.' },
      { title: 'Zero Bloat', desc: 'Handcrafted semantic markup and clean modular CSS without unnecessary library bloat.' },
      { title: 'Deterministic Security', desc: 'Built-in CSRF protection, sanitized user inputs, and SOC-2 compliant practices.' },
    ],
    useCases: ['Enterprise Marketing Sites', 'Custom SaaS Platforms', 'Client Portals', 'E-commerce Flagships', 'Internal Admin Hubs'],
  },
  {
    id: 'mobile',
    slug: 'mobile-app-development',
    category: 'Mobile Apps',
    tag: 'iOS & Android',
    title: 'Native & Cross-Platform Mobile Apps',
    shortDesc: 'Transform your product idea into fluid iOS and Android applications with native 60fps performance and intuitive touch mechanics.',
    fullDesc: 'We develop native and cross-platform mobile apps using React Native and Flutter, engineered for rapid delivery without compromising on 60fps performance, battery efficiency, or native hardware integrations (HealthKit, Geolocation, Bluetooth, Camera, Biometrics).',
    sla: '2–4 Weeks Turnaround',
    deliverables: [
      'iOS & Android Cross-Platform Mobile Applications',
      'Offline-First Local SQLite & Remote Cloud Synchronization',
      'Push Notification Pipelines with Automated Segmentation',
      'In-App Subscriptions, Apple Pay & Google Pay Integrations',
      'Complete App Store & Google Play Store Submission & Compliance',
      'Biometric FaceID / Fingerprint Authentication',
      'Real-Time WebSockets & Telemetry Feeds',
    ],
    techStack: ['React Native', 'Flutter', 'Expo EAS', 'FastAPI', 'SQLite', 'Firebase', 'Apple HealthKit', 'RevenueCat'],
    features: [
      { title: '60 FPS Native Touch', desc: 'Fluid gestures, haptic feedback, and buttery smooth animations.' },
      { title: 'Offline Reliability', desc: 'Full application usability even in zero-connectivity environments with automatic background sync.' },
      { title: 'App Store Pass Guarantee', desc: 'Strict adherence to Apple Human Interface and Google Material 3 guidelines.' },
    ],
    useCases: ['Fintech & Wallet Apps', 'Health & Fitness Tracking', 'On-Demand Service Platforms', 'B2B Field Operations', 'Social & Creator Communities'],
  },
  {
    id: 'ai',
    slug: 'ai-automation-workflows',
    category: 'AI & Automations',
    tag: 'AI & Automations',
    title: 'Autonomous AI Workflows & Enterprise Automation',
    shortDesc: 'Eliminate repetitive manual bottlenecks, ticket queues, and data entry errors with custom autonomous AI pipelines.',
    fullDesc: 'We build autonomous agentic workflows and AI pipelines that connect your existing software ecosystem (CRMs, ERPs, Slack, WhatsApp, Google Workspace, databases). Our systems extract unstructured data, triage inbound requests, generate reports, and trigger deterministic actions 24/7 with zero human delay.',
    sla: '5–10 Days Deployment',
    deliverables: [
      'n8n, Make & Custom Python Autonomous Pipelines',
      'Custom LLM Agents Trained on Proprietary Business Data (RAG)',
      'Automated Lead Qualification & CRM Syncing (HubSpot, Salesforce)',
      'Multi-Channel Support Copilots for WhatsApp & Slack',
      'Deterministic Fail-Safe Fallbacks & Human-in-the-Loop Safeguards',
      'Document AI: Automated PDF/Invoice Data Extraction',
      '24/7 Automated System Health Monitoring & Telemetry',
    ],
    techStack: ['n8n', 'Python', 'OpenAI GPT-4o', 'LangChain', 'FastAPI', 'Make.com', 'Vector DBs (Qdrant/Pinecone)', 'WhatsApp API'],
    features: [
      { title: '90%+ Manual Labor Reduction', desc: 'Autonomous pipelines execute tasks in seconds that previously required hours of human data entry.' },
      { title: 'Zero Hallucination Guardrails', desc: 'Rigid JSON schemas and deterministic validation filters ensure 100% data integrity.' },
      { title: 'Instant ROI', desc: 'Most clients recover their full deployment investment within the first 30 days.' },
    ],
    useCases: ['Freight & Dispatch Logistics', 'Customer Support Triage', 'Invoice & Expense Processing', 'HR Onboarding & Vetting', 'Sales Outreach Enrichment'],
  },
  {
    id: 'hospitality',
    slug: 'restaurant-hospitality-suites',
    category: 'Enterprise & Hospitality Tech',
    tag: 'Hospitality Tech',
    title: 'Restaurant, Café & Hospitality Digital Suites',
    shortDesc: 'Digital menus, dynamic QR ordering, reservations, loyalty, and POS integrations—fully branded and managed for hospitality operators.',
    fullDesc: 'A unified digital operations operating system designed specifically for cafes, high-end restaurants, cloud kitchens, and multi-location food franchises. Increase table turnover, capture customer data, eliminate high third-party aggregator commissions, and streamline kitchen order tickets in real time.',
    sla: '3–7 Days Fast-Track Launch',
    deliverables: [
      'Ultra-Fast Interactive QR Digital Menus (No App Download Needed)',
      'Direct Table Ordering, Takeaway & Delivery Engines',
      'Automated Table Reservation & SMS/WhatsApp Confirmation Bot',
      'Loyalty Stamp Cards & Automated Birthday Rewards',
      'Kitchen Display System (KDS) & Thermal Printer Integration',
      'Staff Role Management & End-of-Day Sales Analytics',
      'Direct WhatsApp Ordering Hub with Instant Payment Links',
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'WebSockets', 'Thermal Print Protocol', 'WhatsApp Business API', 'Razorpay/Stripe'],
    features: [
      { title: 'Zero Aggregator Commissions', desc: 'Keep 100% of your revenue on direct customer takeout and delivery orders.' },
      { title: 'Instant Menu Updates', desc: 'Update prices, 86 sold-out dishes, and launch weekend specials across all tables in 2 clicks.' },
      { title: 'Repeat Diner Engine', desc: 'Automated WhatsApp remarketing that brings back past diners with targeted incentives.' },
    ],
    useCases: ['Fine Dining Restaurants', 'Artisanal Cafes & Bakeries', 'Multi-Outlet QSR Chains', 'Cloud Kitchen Networks', 'Bars & Craft Breweries'],
  },
  {
    id: 'design',
    slug: 'ui-ux-design-systems',
    category: 'UI/UX Design Systems',
    tag: 'UI/UX Design',
    title: 'UI/UX Design Systems & Product Strategy',
    shortDesc: 'Clean, distraction-free interfaces engineered to turn first-time visitors into retained, delighted power users.',
    fullDesc: 'Design is not just decoration—it is the functional architecture of how your customers perceive and interact with your software. We build scalable design systems in Figma with comprehensive design tokens, interactive component libraries, and end-to-end user journey mapping that seamlessly translate into production code.',
    sla: '7–12 Days Delivery',
    deliverables: [
      'Complete Production Figma Design Systems & Token Architecture',
      'Interactive High-Fidelity Clickable Prototypes',
      'User Journey Mapping & Information Architecture',
      'Usability Audits & Friction-Elimination Redesigns',
      'Design-to-Code Production Handoff with Zero Ambiguity',
      'Light & Dark Mode UI Theme Guidelines',
      'Custom Iconography & Responsive Typography Scales',
    ],
    techStack: ['Figma', 'Tokens Studio', 'Principle', 'Design Systems', 'Atomic UI', 'Accessibility (WCAG 2.1)'],
    features: [
      { title: 'Developer-Ready Tokens', desc: 'Tokens match 1:1 with CSS variables and Tailwind classes for flawless code translation.' },
      { title: 'WCAG AAA Accessibility', desc: 'High-contrast typography and clear interactive visual targets for all users.' },
      { title: 'Psychology-Driven UX', desc: 'Strategic visual hierarchies that guide user focus directly toward core conversion actions.' },
    ],
    useCases: ['SaaS Web Applications', 'Mobile App Interfaces', 'Enterprise Internal Portals', 'E-commerce Checkout Optimization', 'Complex Data Dashboards'],
  },
  {
    id: 'cloud-devops',
    slug: 'cloud-devops-infrastructure',
    category: 'Cloud & DevOps',
    tag: 'Cloud & Infrastructure',
    title: 'Cloud Architecture, DevOps & 24/7 Reliability',
    shortDesc: 'Bulletproof cloud infrastructure, automated CI/CD deployment pipelines, and proactive security monitoring.',
    fullDesc: 'We architect scalable, cost-efficient cloud foundations on AWS, GCP, and modern edge platforms (Vercel, Cloudflare, Supabase). We configure automated CI/CD pipelines, container orchestration, DDoS mitigation, automated backups, and real-time telemetry so your digital platform never goes down.',
    sla: 'Ongoing or 1–2 Week Setup',
    deliverables: [
      'AWS / GCP Cloud Infrastructure Architecture & Cost Optimization',
      'Automated GitHub Actions CI/CD Deployment Pipelines',
      'Docker Containerization & Kubernetes Microservices Setup',
      'PostgreSQL / Redis High-Availability Database Clusters',
      'Cloudflare Enterprise CDN Caching & DDoS Shielding',
      'Automated Disaster Recovery & 15-Minute Snapshot Backups',
      'Real-Time Health Monitoring, Uptime Alarms & Log Aggregation',
    ],
    techStack: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions', 'Cloudflare', 'PostgreSQL', 'Datadog/Grafana'],
    features: [
      { title: '99.9% Uptime SLA', desc: 'High-availability multi-region setups with automatic failover.' },
      { title: 'Up to 40% Cloud Cost Reduction', desc: 'Pruning idle resources, optimizing database queries, and leveraging edge caching.' },
      { title: 'Instant Zero-Downtime Releases', desc: 'Ship new features to production in seconds with automated rollback capabilities.' },
    ],
    useCases: ['High-Traffic Consumer Platforms', 'Fintech Security Compliance', 'SaaS Multi-Tenant Infrastructure', 'Legacy System Cloud Migrations'],
  },
  {
    id: 'branding-growth',
    slug: 'branding-digital-growth',
    category: 'Enterprise & Hospitality Tech',
    tag: 'Identity & Growth',
    title: 'Branding, Visual Identity & Automated Content Growth',
    shortDesc: 'Distinctive brand identities paired with automated multi-channel content pipelines that drive real, measurable digital growth.',
    fullDesc: 'Make your business instantly recognizable in a crowded market. We create comprehensive visual identity systems (logos, color palettes, typography, pitch deck kits) and pair them with autonomous social media publishing engines and SEO growth architectures.',
    sla: '7–14 Days Execution',
    deliverables: [
      'Comprehensive Brand Identity Guidelines & Vector Logo Suites',
      'Social Media Visual Templates & Campaign Toolkits',
      'Automated Multi-Platform Content Distribution Pipelines',
      'High-Conversion Pitch Deck & Sales Collateral Design',
      'Organic Technical SEO Architecture & Content Maps',
      'Custom Motion Graphics & Animated Brand Marks',
      'Performance Analytics & Customer Acquisition Tracking',
    ],
    techStack: ['Illustrator', 'Figma', 'After Effects', 'n8n Social Sync', 'Buffer/Hootsuite APIs', 'Google Analytics 4'],
    features: [
      { title: 'Unmistakable Brand Presence', desc: 'Clean, modern, and memorable aesthetics that build immediate trust with high-value clients.' },
      { title: 'Automated Distribution', desc: 'Create once, automatically format and schedule across LinkedIn, Instagram, and X.' },
      { title: 'Data-Backed Iteration', desc: 'Real-time performance metrics tracking engagement, click-throughs, and customer inquiries.' },
    ],
    useCases: ['Early-Stage Startup Launches', 'Established Brand Modernization', 'B2B Thought Leadership Campaigns', 'Direct-to-Consumer Growth'],
  },
];
